# NumPy 101
This notebook introduces the NumPy array, the fundamental data structure of NumPy

Resource: 
https://www.scipy-lectures.org/intro/numpy/index.html

### What is a NumPy array?

In [1]:
import numpy as np
a = np.array([0, 1, 2, 3])
a

array([0, 1, 2, 3])

### Numpy is fast!

In [2]:
#Construct a list of values from 0 to 999
L = range(1000)

In [3]:
#How fast to loop through all LIST items and compute its square
%timeit [i**2 for i in L]

457 µs ± 29.6 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [4]:
#Construct an ARRAY of values from 0 to 999
a = np.arange(1000)

In [5]:
#How fast to loop through all ARRAY items and compute its square
%timeit a**2

1.99 µs ± 160 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


### Ways to create NumPy arrays...

* 1D array

In [6]:
a = np.array([0, 1, 2, 3])
a

array([0, 1, 2, 3])

In [7]:
a.ndim

1

In [8]:
a.shape

(4,)

* 2D/3D array

In [9]:
b = np.array([[0, 1, 2], [3, 4, 5]])    # 2 x 3 array
b

array([[0, 1, 2],
       [3, 4, 5]])

In [10]:
b.ndim

2

In [11]:
b.shape

(2, 3)

#### Special arrays
 * Evenly spaced (min, max, and step)

In [12]:
a = np.arange(10) # 0 .. n-1  (!)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
b = np.arange(1, 9, 2) # start, end (exclusive), step
b

array([1, 3, 5, 7])

 * Evenly spaced (min, max, and number of values)

In [14]:
c = np.linspace(0, 1, 6)   # start, end, num-points
c

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

In [15]:
d = np.linspace(0, 1, 5, endpoint=False)
d

array([0. , 0.2, 0.4, 0.6, 0.8])

 * Arrays of all 1s, zeros, "eye", "diag"

In [16]:
a = np.ones((3, 3))  # reminder: (3, 3) is a tuple
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [17]:
b = np.zeros((2, 2))
b

array([[0., 0.],
       [0., 0.]])

In [18]:
c = np.eye(3)
c

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [19]:
d = np.diag(np.array([1, 2, 3, 4]))
d

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

 * Arrays of random values

In [20]:
a = np.random.rand(4)       # uniform in [0, 1]
a  

array([0.47831811, 0.29348927, 0.7205143 , 0.01649263])

In [21]:
b = np.random.randn(4)      # Gaussian
b  

array([ 0.83231841, -0.35585773, -0.58247869, -1.02354905])

In [22]:
np.random.seed(1234)        # Setting the random seed